[server]
hosts = 127.0.0.1:5232, __TAILSCALE_IP__:5232
max_connections = 8
timeout = 30

[auth]
type = htpasswd
htpasswd_filename = __HOME__/.config/radicale/users
htpasswd_encryption = bcrypt

[storage]
filesystem_folder = __HOME__/.local/share/radicale/collections
max_sync_token_age = 2592000

[logging]
level = info
